version: '3.8'

services:
  users:
    build: ./users
    ports:
      - "5001:5001"
    volumes:
      - ./users/users.json:/app/users.json
      - ./certs/key.pem:/app/key.pem
      - ./certs/cert.pem:/app/cert.pem
    environment:
      - JWT_SECRET=senha12345678
      - INTERNAL_KEY=internal-secret

  products_primary:
    build: ./products
    ports:
      - "5002:5002"
    volumes:
      - ./products/products_5002.json:/app/products_5002.json
      - ./certs/key.pem:/app/key.pem
      - ./certs/cert.pem:/app/cert.pem
    environment:
      - PORT=5002
      - JWT_SECRET=senha12345678
      - INTERNAL_KEY=internal-secret

  products_replica:
    build: ./products
    ports:
      - "5012:5012"
    volumes:
      - ./products/products_5012.json:/app/products_5012.json
      - ./certs/key.pem:/app/key.pem
      - ./certs/cert.pem:/app/cert.pem
    environment:
      - PORT=5012
      - JWT_SECRET=senha12345678
      - INTERNAL_KEY=internal-secret

  orders:
    build: ./orders
    ports:
      - "5003:5003"
    volumes:
      - ./orders/orders.json:/app/orders.json
      - ./certs/key.pem:/app/key.pem
      - ./certs/cert.pem:/app/cert.pem
    environment:
      - JWT_SECRET=senha12345678
      - INTERNAL_KEY=internal-secret
      - PRODUCTS_HOST=products_primary
    depends_on:
      - products_primary

  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    volumes:
      - ./certs/key.pem:/app/key.pem
      - ./certs/cert.pem:/app/cert.pem
    environment:
      - JWT_SECRET=senha12345678
      - USERS_HOST=users
      - PRODUCTS_HOST=products_primary
      - PRODUCTS_REPLICA_HOST=products_replica
      - ORDERS_HOST=orders
      - INTERNAL_KEY=internal-secret
    depends_on:
      - users
      - products_primary
      - products_replica
      - orders
